python eval.py -savepath "./Experiment1/GRU/4/Run1/" 
python eval.py -savepath "./Experiment1/GRU/4/Run2/" 
python eval.py -savepath "./Experiment1/GRU/4/Run3/" 
python eval.py -savepath "./Experiment1/GRU/4/Run4/"  
python eval.py -savepath "./Experiment1/GRU/4/Run5/" 
python eval.py -savepath "./Experiment1/GRU/4/Run6/" 
python eval.py -savepath "./Experiment1/GRU/4/Run7/" 
python eval.py -savepath "./Experiment1/GRU/4/Run8/" 
python eval.py -savepath "./Experiment1/GRU/4/Run9/" 
python eval.py -savepath "./Experiment1/GRU/4/Run10/"
python eval.py -savepath "./Experiment1/GRU/8/Run1/" 
python eval.py -savepath "./Experiment1/GRU/8/Run2/" 
python eval.py -savepath "./Experiment1/GRU/8/Run3/" 
python eval.py -savepath "./Experiment1/GRU/8/Run4/"  
python eval.py -savepath "./Experiment1/GRU/8/Run5/" 
python eval.py -savepath "./Experiment1/GRU/8/Run6/" 
python eval.py -savepath "./Experiment1/GRU/8/Run7/" 
python eval.py -savepath "./Experiment1/GRU/8/Run8/" 
python eval.py -savepath "./Experiment1/GRU/8/Run9/" 
python eval.py -savepath "./Experiment1/GRU/8/Run10/"
python eval.py -savepath "./Experiment1/GRU/16/Run1/" 
python eval.py -savepath "./Experiment1/GRU/16/Run2/" 
python eval.py -savepath "./Experiment1/GRU/16/Run3/" 
python eval.py -savepath "./Experiment1/GRU/16/Run4/"  
python eval.py -savepath "./Experiment1/GRU/16/Run5/" 
python eval.py -savepath "./Experiment1/GRU/16/Run6/" 
python eval.py -savepath "./Experiment1/GRU/16/Run7/" 
python eval.py -savepath "./Experiment1/GRU/16/Run8/" 
python eval.py -savepath "./Experiment1/GRU/16/Run9/" 
python eval.py -savepath "./Experiment1/GRU/16/Run10/"
python eval.py -savepath "./Experiment1/GRU/32/Run1/" 
python eval.py -savepath "./Experiment1/GRU/32/Run2/" 
python eval.py -savepath "./Experiment1/GRU/32/Run3/" 
python eval.py -savepath "./Experiment1/GRU/32/Run4/"  
python eval.py -savepath "./Experiment1/GRU/32/Run5/" 
python eval.py -savepath "./Experiment1/GRU/32/Run6/" 
python eval.py -savepath "./Experiment1/GRU/32/Run7/" 
python eval.py -savepath "./Experiment1/GRU/32/Run8/" 
python eval.py -savepath "./Experiment1/GRU/32/Run9/" 
python eval.py -savepath "./Experiment1/GRU/32/Run10/"
python eval.py -model 'LSTM' -savepath "./Experiment1/LSTM/4/Run1/" 
python eval.py -model 'LSTM' -savepath "./Experiment1/LSTM/4/Run2/" 
python eval.py -model 'LSTM' -savepath "./Experiment1/LSTM/4/Run3/" 
python eval.py -model 'LSTM' -savepath "./Experiment1/LSTM/4/Run4/"  
python eval.py -model 'LSTM' -savepath "./Experiment1/LSTM/4/Run5/" 
python eval.py -model 'LSTM' -savepath "./Experiment1/LSTM/4/Run6/" 
python eval.py -model 'LSTM' -savepath "./Experiment1/LSTM/4/Run7/" 
python eval.py -model 'LSTM' -savepath "./Experiment1/LSTM/4/Run8/" 
python eval.py -model 'LSTM' -savepath "./Experiment1/LSTM/4/Run9/" 
python eval.py -model 'LSTM' -savepath "./Experiment1/LSTM/4/Run10/"
python eval.py -model 'LSTM' -savepath "./Experiment1/LSTM/8/Run1/" 
python eval.py -model 'LSTM' -savepath "./Experiment1/LSTM/8/Run2/" 
python eval.py -model 'LSTM' -savepath "./Experiment1/LSTM/8/Run3/" 
python eval.py -model 'LSTM' -savepath "./Experiment1/LSTM/8/Run4/"  
python eval.py -model 'LSTM' -savepath "./Experiment1/LSTM/8/Run5/" 
python eval.py -model 'LSTM' -savepath "./Experiment1/LSTM/8/Run6/" 
python eval.py -model 'LSTM' -savepath "./Experiment1/LSTM/8/Run7/" 
python eval.py -model 'LSTM' -savepath "./Experiment1/LSTM/8/Run8/" 
python eval.py -model 'LSTM' -savepath "./Experiment1/LSTM/8/Run9/" 
python eval.py -model 'LSTM' -savepath "./Experiment1/LSTM/8/Run10/"
python eval.py -model 'LSTM' -savepath "./Experiment1/LSTM/16/Run1/" 
python eval.py -model 'LSTM' -savepath "./Experiment1/LSTM/16/Run2/" 
python eval.py -model 'LSTM' -savepath "./Experiment1/LSTM/16/Run3/" 
python eval.py -model 'LSTM' -savepath "./Experiment1/LSTM/16/Run4/"  
python eval.py -model 'LSTM' -savepath "./Experiment1/LSTM/16/Run5/" 
python eval.py -model 'LSTM' -savepath "./Experiment1/LSTM/16/Run6/" 
python eval.py -model 'LSTM' -savepath "./Experiment1/LSTM/16/Run7/" 
python eval.py -model 'LSTM' -savepath "./Experiment1/LSTM/16/Run8/" 
python eval.py -model 'LSTM' -savepath "./Experiment1/LSTM/16/Run9/" 
python eval.py -model 'LSTM' -savepath "./Experiment1/LSTM/16/Run10/"
python eval.py -model 'LSTM' -savepath "./Experiment1/LSTM/32/Run1/" 
python eval.py -model 'LSTM' -savepath "./Experiment1/LSTM/32/Run2/" 
python eval.py -model 'LSTM' -savepath "./Experiment1/LSTM/32/Run3/" 
python eval.py -model 'LSTM' -savepath "./Experiment1/LSTM/32/Run4/"  
python eval.py -model 'LSTM' -savepath "./Experiment1/LSTM/32/Run5/" 
python eval.py -model 'LSTM' -savepath "./Experiment1/LSTM/32/Run6/" 
python eval.py -model 'LSTM' -savepath "./Experiment1/LSTM/32/Run7/" 
python eval.py -model 'LSTM' -savepath "./Experiment1/LSTM/32/Run8/" 
python eval.py -model 'LSTM' -savepath "./Experiment1/LSTM/32/Run9/" 
python eval.py -model 'LSTM' -savepath "./Experiment1/LSTM/32/Run10/"
python eval.py -model 'RNN' -savepath "./Experiment1/RNN/4/Run1/" 
python eval.py -model 'RNN' -savepath "./Experiment1/RNN/4/Run2/" 
python eval.py -model 'RNN' -savepath "./Experiment1/RNN/4/Run3/" 
python eval.py -model 'RNN' -savepath "./Experiment1/RNN/4/Run4/"  
python eval.py -model 'RNN' -savepath "./Experiment1/RNN/4/Run5/" 
python eval.py -model 'RNN' -savepath "./Experiment1/RNN/4/Run6/" 
python eval.py -model 'RNN' -savepath "./Experiment1/RNN/4/Run7/" 
python eval.py -model 'RNN' -savepath "./Experiment1/RNN/4/Run8/" 
python eval.py -model 'RNN' -savepath "./Experiment1/RNN/4/Run9/" 
python eval.py -model 'RNN' -savepath "./Experiment1/RNN/4/Run10/"
python eval.py -model 'RNN' -savepath "./Experiment1/RNN/8/Run1/" 
python eval.py -model 'RNN' -savepath "./Experiment1/RNN/8/Run2/" 
python eval.py -model 'RNN' -savepath "./Experiment1/RNN/8/Run3/" 
python eval.py -model 'RNN' -savepath "./Experiment1/RNN/8/Run4/"  
python eval.py -model 'RNN' -savepath "./Experiment1/RNN/8/Run5/" 
python eval.py -model 'RNN' -savepath "./Experiment1/RNN/8/Run6/" 
python eval.py -model 'RNN' -savepath "./Experiment1/RNN/8/Run7/" 
python eval.py -model 'RNN' -savepath "./Experiment1/RNN/8/Run8/" 
python eval.py -model 'RNN' -savepath "./Experiment1/RNN/8/Run9/" 
python eval.py -model 'RNN' -savepath "./Experiment1/RNN/8/Run10/"
python eval.py -model 'RNN' -savepath "./Experiment1/RNN/16/Run1/" 
python eval.py -model 'RNN' -savepath "./Experiment1/RNN/16/Run2/" 
python eval.py -model 'RNN' -savepath "./Experiment1/RNN/16/Run3/" 
python eval.py -model 'RNN' -savepath "./Experiment1/RNN/16/Run4/"  
python eval.py -model 'RNN' -savepath "./Experiment1/RNN/16/Run5/" 
python eval.py -model 'RNN' -savepath "./Experiment1/RNN/16/Run6/" 
python eval.py -model 'RNN' -savepath "./Experiment1/RNN/16/Run7/" 
python eval.py -model 'RNN' -savepath "./Experiment1/RNN/16/Run8/" 
python eval.py -model 'RNN' -savepath "./Experiment1/RNN/16/Run9/" 
python eval.py -model 'RNN' -savepath "./Experiment1/RNN/16/Run10/"
python eval.py -model 'RNN' -savepath "./Experiment1/RNN/32/Run1/" 
python eval.py -model 'RNN' -savepath "./Experiment1/RNN/32/Run2/" 
python eval.py -model 'RNN' -savepath "./Experiment1/RNN/32/Run3/" 
python eval.py -model 'RNN' -savepath "./Experiment1/RNN/32/Run4/"  
python eval.py -model 'RNN' -savepath "./Experiment1/RNN/32/Run5/" 
python eval.py -model 'RNN' -savepath "./Experiment1/RNN/32/Run6/" 
python eval.py -model 'RNN' -savepath "./Experiment1/RNN/32/Run7/" 
python eval.py -model 'RNN' -savepath "./Experiment1/RNN/32/Run8/" 
python eval.py -model 'RNN' -savepath "./Experiment1/RNN/32/Run9/" 
python eval.py -model 'RNN' -savepath "./Experiment1/RNN/32/Run10/"
python eval.py -model 'RNN' -savepath "./Experiment1/RNN/64/Run1/" 
python eval.py -model 'RNN' -savepath "./Experiment1/RNN/64/Run2/" 
python eval.py -model 'RNN' -savepath "./Experiment1/RNN/64/Run3/" 
python eval.py -model 'RNN' -savepath "./Experiment1/RNN/64/Run4/"  
python eval.py -model 'RNN' -savepath "./Experiment1/RNN/64/Run5/" 
python eval.py -model 'RNN' -savepath "./Experiment1/RNN/64/Run6/" 
python eval.py -model 'RNN' -savepath "./Experiment1/RNN/64/Run7/" 
python eval.py -model 'RNN' -savepath "./Experiment1/RNN/64/Run8/" 
python eval.py -model 'RNN' -savepath "./Experiment1/RNN/64/Run9/" 
python eval.py -model 'RNN' -savepath "./Experiment1/RNN/64/Run10/"